name: radio_button_form_field
description: A Flutter Package to create radio buttons as FormFields, each contained in a ListTile with the button as the Leading Widget.
version: 0.0.4
homepage: https://github.com/Cali0707/radio_button_form_field/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


